name: '12.4'
channels:
  - pyg
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=3_kmp_llvm
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.11.18=py310h89163eb_0
  - aiosignal=1.3.2=pyhd8ed1ab_0
  - alsa-lib=1.2.8=h166bdaf_0
  - anyio=4.9.0=pyh29332c3_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_1
  - argon2-cffi-bindings=21.2.0=py310ha75aee5_5
  - arrow=1.3.0=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - async-lru=2.0.5=pyh29332c3_0
  - async-timeout=5.0.1=pyhd8ed1ab_1
  - attr=2.5.1=h166bdaf_1
  - attrs=25.3.0=pyh71513ae_0
  - babel=2.17.0=pyhd8ed1ab_0
  - beautifulsoup4=4.13.4=pyha770c72_0
  - blas=2.116=mkl
  - blas-devel=3.9.0=16_linux64_mkl
  - bleach=6.2.0=pyh29332c3_4
  - bleach-with-css=6.2.0=h82add2a_4
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - brotli-python=1.1.0=py310hf71b8c6_2
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.4.26=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.16.0=ha61ee94_1014
  - certifi=2025.1.31=pyhd8ed1ab_0
  - cffi=1.17.1=py310h8deb56e_0
  - charset-normalizer=3.4.2=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.2=pyhd8ed1ab_1
  - contourpy=1.3.2=py310h3788b33_0
  - cpython=3.10.17=py310hd8ed1ab_0
  - cuda-cudart=12.4.127=0
  - cuda-cupti=12.4.127=0
  - cuda-libraries=12.4.1=0
  - cuda-nvrtc=12.4.127=0
  - cuda-nvtx=12.4.127=0
  - cuda-opencl=12.9.19=0
  - cuda-runtime=12.4.1=0
  - cuda-version=12.9=3
  - cycler=0.12.1=pyhd8ed1ab_1
  - dbus=1.13.6=h5008d03_3
  - debugpy=1.8.14=py310hf71b8c6_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.2.0=pyhd8ed1ab_0
  - expat=2.7.0=h5888daf_0
  - fastcore=1.8.1=pyh29332c3_0
  - ffmpeg=4.3=hf484d3e_0
  - fftw=3.3.10=nompi_hf1063bd_110
  - filelock=3.18.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.57.0=py310h89163eb_0
  - fqdn=1.5.1=pyhd8ed1ab_1
  - freetype=2.12.1=h267a509_2
  - frozenlist=1.5.0=py310h89163eb_1
  - fsspec=2025.3.2=pyhd8ed1ab_0
  - gettext=0.24.1=h5888daf_0
  - gettext-tools=0.24.1=h5888daf_0
  - glib=2.80.2=hf974151_0
  - glib-tools=2.80.2=hb6ce0ca_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py310he8512ff_0
  - gnutls=3.6.13=h85f3911_1
  - graphite2=1.3.13=h59595ed_1003
  - gst-plugins-base=1.22.0=h4243ec0_2
  - gstreamer=1.22.0=h25f0c4b_2
  - gstreamer-orc=0.4.41=h17648ed_0
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.2.0=pyhd8ed1ab_0
  - harfbuzz=6.0.0=h8e241bc_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=70.1=h27087fc_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.6.1=pyha770c72_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=8.36.0=pyh907856f_0
  - ipywidgets=8.1.6=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_1
  - jack=1.9.22=h11f4161_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.0=pyhd8ed1ab_0
  - jpeg=9e=h166bdaf_2
  - json5=0.12.0=pyhd8ed1ab_0
  - jsonpointer=3.0.0=py310hff52083_1
  - jsonschema=4.23.0=pyhd8ed1ab_1
  - jsonschema-specifications=2025.4.1=pyh29332c3_0
  - jsonschema-with-format-nongpl=4.23.0=hd8ed1ab_1
  - jupyter-lsp=2.2.5=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - jupyter_events=0.12.0=pyh29332c3_0
  - jupyter_server=2.15.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.5.3=pyhd8ed1ab_1
  - jupyterlab=4.4.1=pyhd8ed1ab_0
  - jupyterlab_pygments=0.3.0=pyhd8ed1ab_2
  - jupyterlab_server=2.27.3=pyhd8ed1ab_1
  - jupyterlab_widgets=3.0.14=pyhd8ed1ab_0
  - k3d=2.16.1=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.7=py310h3788b33_0
  - krb5=1.20.1=h81ceb04_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.15=hfd0df8a_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - lerc=4.0.0=h0aef613_1
  - libasprintf=0.24.1=h8e693c7_0
  - libasprintf-devel=0.24.1=h8e693c7_0
  - libblas=3.9.0=16_linux64_mkl
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcap=2.67=he9d0100_0
  - libcblas=3.9.0=16_linux64_mkl
  - libclang=15.0.7=default_h127d8a8_5
  - libclang13=15.0.7=default_h5d6823c_5
  - libcublas=12.4.5.8=0
  - libcufft=11.2.1.3=0
  - libcufile=1.14.0.30=4
  - libcups=2.3.3=h36d4200_3
  - libcurand=10.3.10.19=0
  - libcusolver=11.6.1.9=0
  - libcusparse=12.3.1.170=0
  - libdb=6.2.32=h9c3ff4c_0
  - libdeflate=1.17=h0b41bf4_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libevent=2.1.10=h28343ad_4
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libflac=1.4.3=h59595ed_0
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgcrypt=1.11.0=ha770c72_2
  - libgcrypt-devel=1.11.0=hb9d3cd8_2
  - libgcrypt-lib=1.11.0=hb9d3cd8_2
  - libgcrypt-tools=1.11.0=hb9d3cd8_2
  - libgettextpo=0.24.1=h5888daf_0
  - libgettextpo-devel=0.24.1=h5888daf_0
  - libgfortran=14.2.0=h69a702a_2
  - libgfortran-ng=14.2.0=h69a702a_2
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libglib=2.80.2=hf974151_0
  - libgomp=14.2.0=h767d61c_2
  - libgpg-error=1.55=h3f2d84a_0
  - libhwloc=2.9.1=hd6dc26d_0
  - libiconv=1.18=h4ce23a2_1
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - liblapack=3.9.0=16_linux64_mkl
  - liblapacke=3.9.0=16_linux64_mkl
  - libllvm15=15.0.7=hadd5161_1
  - libltdl=2.4.3a=h5888daf_0
  - liblzma=5.8.1=hb9d3cd8_0
  - liblzma-devel=5.8.1=hb9d3cd8_0
  - libnpp=12.2.5.30=0
  - libnsl=2.0.1=hd590300_0
  - libnvfatbin=12.9.19=0
  - libnvjitlink=12.4.127=0
  - libnvjpeg=12.3.1.117=0
  - libogg=1.3.5=hd0c01bc_1
  - libopus=1.5.2=hd0c01bc_0
  - libpng=1.6.43=h2797004_0
  - libpq=15.3=hbcd7760_1
  - libsndfile=1.2.2=hc60ed4a_1
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.46.0=hde9e2c9_0
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-ng=14.2.0=h4852527_2
  - libsystemd0=253=h8c4010b_1
  - libtiff=4.5.0=h6adf6a1_2
  - libtool=2.5.4=h5888daf_0
  - libudev1=253=h0b41bf4_1
  - libuuid=2.38.1=h0b41bf4_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.13=h7f98852_1004
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.5.0=h79f4944_1
  - libxml2=2.10.3=hca2bb57_4
  - libzlib=1.2.13=h4ab18f5_6
  - lightning=2.5.1.post0=pyhd8ed1ab_0
  - lightning-utilities=0.14.3=pyhd8ed1ab_0
  - llvm-openmp=15.0.7=h0cdce71_0
  - lz4-c=1.9.4=hcb278e6_0
  - markupsafe=3.0.2=py310h89163eb_1
  - matplotlib=3.9.1=py310hff52083_1
  - matplotlib-base=3.9.1=py310hf02ac8c_2
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mistune=3.1.3=pyh29332c3_0
  - mkl=2022.1.0=h84fe81f_915
  - mkl-devel=2022.1.0=ha770c72_916
  - mkl-include=2022.1.0=h84fe81f_915
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpg123=1.32.9=hc50e24c_0
  - mpmath=1.3.0=pyhd8ed1ab_1
  - msgpack-python=1.1.0=py310h3788b33_0
  - multidict=6.4.3=py310h89163eb_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=8.0.33=hf1915f5_6
  - mysql-libs=8.0.33=hca2cd23_6
  - nbclient=0.10.2=pyhd8ed1ab_0
  - nbconvert-core=7.16.6=pyh29332c3_0
  - nbformat=5.10.4=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nettle=3.6=he412f7d_0
  - networkx=3.4.2=pyh267e887_2
  - ninja=1.12.1=hff21bea_1
  - notebook-shim=0.2.4=pyhd8ed1ab_1
  - nspr=4.36=h5888daf_0
  - nss=3.100=hca3bf56_0
  - numpy=2.2.5=py310hefbff90_0
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2024.10.24=h5888daf_0
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.1.8=h7b32b05_0
  - overrides=7.7.0=pyhd8ed1ab_1
  - packaging=24.2=pyhd8ed1ab_2
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_1
  - pcre2=10.43=hcad00b1_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=9.4.0=py310h023d228_1
  - pip=25.1.1=pyh8b19718_0
  - pixman=0.46.0=h29eaf8c_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_2
  - platformdirs=4.3.7=pyh29332c3_0
  - ply=3.11=pyhd8ed1ab_3
  - prometheus_client=0.21.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - propcache=0.3.1=py310h89163eb_0
  - psutil=7.0.0=py310ha75aee5_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pulseaudio=16.1=hcb278e6_3
  - pulseaudio-client=16.1=h5195f5e_3
  - pulseaudio-daemon=16.1=ha8d29e2_3
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pyg=2.6.1=py310_torch_2.4.0_cu124
  - pygments=2.19.1=pyhd8ed1ab_0
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pyqt=5.15.9=py310h04931ad_5
  - pyqt5-sip=12.12.2=py310hc6cd4ac_5
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.10.13=hd12c33a_0_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-fastjsonschema=2.21.1=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python_abi=3.10=7_cp310
  - pytorch=2.4.0=py3.10_cuda12.4_cudnn9.1.0_0
  - pytorch-cuda=12.4=hc786d27_7
  - pytorch-lightning=2.5.1.post0=pyh2a12c56_0
  - pytorch-mutex=1.0=cuda
  - pytorch-scatter=2.1.2=py310_torch_2.4.0_cu124
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py310h89163eb_2
  - pyzmq=26.2.0=py310h71f11fc_1
  - qhull=2020.2=h434a139_5
  - qt-main=5.15.8=h5d23da1_6
  - readline=8.2=h8c095d6_2
  - referencing=0.36.2=pyh29332c3_0
  - requests=2.32.3=pyhd8ed1ab_1
  - rfc3339-validator=0.1.4=pyhd8ed1ab_1
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rpds-py=0.24.0=py310hc1293b2_0
  - scikit-learn=1.6.1=py310h27f47ee_0
  - scipy=1.15.2=py310h1d65ade_0
  - send2trash=1.8.3=pyh0d859eb_1
  - setuptools=80.1.0=pyhff2d567_0
  - sip=6.7.12=py310hc6cd4ac_0
  - six=1.17.0=pyhd8ed1ab_0
  - sniffio=1.3.1=pyhd8ed1ab_1
  - soupsieve=2.5=pyhd8ed1ab_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - sympy=1.14.0=pyh2585a3b_105
  - tbb=2021.9.0=hf52228f_0
  - terminado=0.18.1=pyh0d859eb_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tinycss2=1.4.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - toml=0.10.2=pyhd8ed1ab_1
  - tomli=2.2.1=pyhd8ed1ab_1
  - torchaudio=2.4.0=py310_cu124
  - torchmetrics=1.7.1=pyhd8ed1ab_0
  - torchtriton=3.0.0=py310
  - torchvision=0.19.0=py310_cu124
  - tornado=6.4.2=py310ha75aee5_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - traittypes=0.2.1=pyh9f0ad1d_2
  - types-python-dateutil=2.9.0.20241206=pyhd8ed1ab_0
  - typing-extensions=4.13.2=h0e9735f_0
  - typing_extensions=4.13.2=pyh29332c3_0
  - typing_utils=0.1.0=pyhd8ed1ab_1
  - tzdata=2025b=h78e105d_0
  - unicodedata2=16.0.0=py310ha75aee5_0
  - uri-template=1.3.0=pyhd8ed1ab_1
  - urllib3=2.4.0=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - webcolors=24.11.1=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_3
  - websocket-client=1.8.0=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - widgetsnbextension=4.0.14=pyhd8ed1ab_0
  - xcb-util=0.4.0=h516909a_0
  - xcb-util-image=0.4.0=h166bdaf_0
  - xcb-util-keysyms=0.4.0=h516909a_0
  - xcb-util-renderutil=0.3.9=h166bdaf_0
  - xcb-util-wm=0.4.1=h516909a_0
  - xkeyboard-config=2.38=h0b41bf4_0
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.4=h0b41bf4_0
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xproto=7.0.31=hb9d3cd8_1008
  - xz=5.8.1=hbcc6ac9_0
  - xz-gpl-tools=5.8.1=hbcc6ac9_0
  - xz-tools=5.8.1=hb9d3cd8_0
  - yaml=0.2.5=h7f98852_2
  - yarl=1.20.0=py310h89163eb_0
  - zeromq=4.3.5=h59595ed_1
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.2.13=h4ab18f5_6
  - zstandard=0.23.0=py310ha75aee5_2
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - backports-cached-property==1.0.2
      - blessings==1.7
      - cachetools==5.5.2
      - chamfer==2.0.0
      - chardet==5.2.0
      - codecov==2.1.13
      - coloredlogs==15.0.1
      - colour-runner==0.1.1
      - coverage==7.8.0
      - deepdiff==8.4.2
      - distlib==0.3.9
      - emd-ext==0.0.0
      - humanfriendly==10.0
      - iopath==0.1.10
      - orderly-set==5.4.0
      - pluggy==1.5.0
      - portalocker==3.1.1
      - pyproject-api==1.9.0
      - pytorch3d==0.7.8
      - rootpath==0.1.1
      - termcolor==3.1.0
      - torchsparse==2.1.0
      - tox==4.25.0
      - virtualenv==20.30.0
prefix: /opt/conda/envs/12.4
